---
- name: Install PPA
  become: yes
  become_user: root
  apt_repository: repo='ppa:ondrej/php' state=present

- name: Update apt
  become: yes
  become_user: root
  apt: update_cache=yes

- name: Install Git
  apt: name=git state=present

- name: Install PHP
  become: yes
  become_user: root
  action: apt pkg={{ item }} state=present
  with_items:
    - php-cli
    - php-xml
    - php-xdebug

- name: Set php_executable variable to a default if not defined.
  set_fact:
    php_executable: php
  when: php_executable is not defined

- name: Check if Composer is installed.
  stat: "path={{ composer_path }}"
  register: composer_bin

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: not composer_bin.stat.exists

- name: Run Composer installer.
  command: >
    {{ php_executable }} composer-installer.php {% if composer_version != '' %} --version={{ composer_version }}{% endif %}
    chdir=/tmp
  when: not composer_bin.stat.exists

- name: Move Composer into globally-accessible location.
  shell: >
    mv /tmp/composer.phar {{ composer_path }}
    creates={{ composer_path }}
  when: not composer_bin.stat.exists

- name: Ensure composer directory exists.
  file:
    path: "{{ composer_home_path }}"
    owner: "{{ composer_home_owner }}"
    group: "{{ composer_home_group }}"
    state: directory

- name: Install dependencies with composer
  command: composer install
  args:
    chdir: /opt/software/tdd-php
